name: NeDisguise
version: 1.0
main: me.nedayazady.NeDisguise
api-version: 1.13
depend: [LuckPerms]
commands:
  disguise:
    description: Opens the disguise menu.
    permission: core.command.disguise
    aliases: [nick]
  undisguise:
    description: Removes your current disguise.
    permission: core.command.undisguise
    aliases: [unnick]
  redisguise:
    description: Reapplies your previous disguise.
    permission: core.command.redisguise
  user:
    description: Rank disguises a player.
    permission: core.command.user.disguise
  disguiseadmin:
    description: Admin disguise commands.
    permission: core.command.disguiseadmin
